//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vault.Validators;

/// <summary>
/// A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class VaultOptionsResources
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal VaultOptionsResources()
    {
    }

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vault.Validators.VaultOptionsResources", typeof(VaultOptionsResources).Assembly);
                resourceMan = temp;
            }

            return resourceMan;
        }
    }

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }

        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration doit être de type VaultAwsConfiguration pour l'authentification AWS_IAM.
    /// </summary>
    public static string Configuration_AWS_IAM_CheckType
    {
        get
        {
            return ResourceManager.GetString("Configuration_AWS_IAM_CheckType", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to Pour l'authentification Custom, Configuration doit être une instance de VaultDefaultConfiguration (pas VaultLocalConfiguration ou VaultAwsConfiguration).
    /// </summary>
    public static string Configuration_CUSTOM_CheckType
    {
        get
        {
            return ResourceManager.GetString("Configuration_CUSTOM_CheckType", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration doit être de type VaultLocalConfiguration pour l'authentification Local.
    /// </summary>
    public static string Configuration_Local_CheckType
    {
        get
        {
            return ResourceManager.GetString("Configuration_Local_CheckType", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration Configuration:Environment est requise.
    /// </summary>
    public static string Environment_Not_Empty
    {
        get
        {
            return ResourceManager.GetString("Environment_Not_Empty", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration Configuration:MountPoint est requise.
    /// </summary>
    public static string MountPoint_Not_Empty
    {
        get
        {
            return ResourceManager.GetString("MountPoint_Not_Empty", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to Configuration doit être défini.
    /// </summary>
    public static string Vault_Configuration_Undefined
    {
        get
        {
            return ResourceManager.GetString("Vault_Configuration_Undefined", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to CustomAuthMethodInfo doit être défini lorsque AuthenticationType = Custom.
    /// </summary>
    public static string Vault_CustomAuthMethodInfo_Undefined
    {
        get
        {
            return ResourceManager.GetString("Vault_CustomAuthMethodInfo_Undefined", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration Vault:AuthenticationType ne peut pas être 'None' lorsque Vault est activé.
    /// </summary>
    public static string VaultAuthenticationType_Not_In_Range
    {
        get
        {
            return ResourceManager.GetString("VaultAuthenticationType_Not_In_Range", resourceCulture)!;
        }
    }

    /// <summary>
    /// Looks up a localized string similar to La configuration Configuration:VaultUrl est requise.
    /// </summary>
    public static string VaultUrl_Not_Empty
    {
        get
        {
            return ResourceManager.GetString("VaultUrl_Not_Empty", resourceCulture)!;
        }
    }
}
